language: node_js
node_js:
- stable
- '7.0'
before_script:
- npm run lint
after_success:
- npm run coveralls
notifications:
  slack:
    secure: rsOoA3PAPfEZX0Lq/XrISh/Tkcsg9oCpp04bSPcDVTRXhCBgwbF8S2ZiAs1ueiLHQ5h9AId/ozjeRaRgyEPXbgQUFKMLtNEe/oDiOrwe13v64nZq94riYiRuGHVeriRdcAvIi7qZcrx60ED7OeOdAH0Gvi5L6ceSrzlSb5Sqhs496rUFGY+K+PqmHsIadqWFCbnQyakZ/4wj5e0ZB/D3y9o1gZxoBSjQ+EaP0p1EM0YrZg4nALQTL8AR9jhY/X8Aj+25MriWyqSUvyBOer1NjF0rCYcqJntUIF2nQL5Xa9evmCQ1pURTWaVQA3KwbFqpPyY6x3PgXrHErCAZ/Cunq9lev8cdjDuVIoxS0LUi55jvWMQ/C0wvaJO0+ZxNnzyGkKP4IB6Qok96MjzPbVQYFNHcpCuI+xiP/vu5+6r7rb12/2xeNFRTPG9z5wN/DHYXgY9pkN298sTAXxcmh3YnSVKiUBBl19ZFJ2lqVqXTFQoQls7jCQKRG4k5PkeyaEcvIas+NoQ8/xyFeVLqhWvaO95aG8frJt5qapkA1W2waxshnRyYn4Z/jCD8lIDmSzDT2H0kmIV9PXsaIs/pSn3W/ge32naftIfWOX3ANeOyNQI6ZzwcE5VMoKMuNSnq1G49ZaZoHmTGymhAia4Kr0zi9wIPb4CeqHtOzuYCApvx7JA=
